import { useState, useEffect } from "react";
import API from "../../api";

const CLASSES = ["Class 1", "Class 2", "Class 3", ];
const DIVISIONS = ["A", "B", "C"];
const SUBJECTS = ["English", "Maths", "Science", ];

export default function StudentForm({ initialData = {}, onClose, onSubmit }) {
  // Initialize form with proper structure
  const [formData, setFormData] = useState({
    user_code: initialData.user_code || "",
    admission_no: initialData.admission_no || "",
    name: initialData.name || "",
    email: initialData.email || "",
    password: initialData.password || "",
    class: initialData.class || "",
    division: initialData.division || "",
    gender: initialData.gender || "M",
    parent_name: initialData.parent_name || "",
    parent_email: initialData.parent_email || "",
    subjects: initialData.subjects || [],
    academic_year: initialData.academic_year || "2024-25"
  });

  const [message, setMessage] = useState(""); // Add message state
  const [loading, setLoading] = useState(false); // Add loading state

  const handleSubmit = async (e) => { // Make this async
    e.preventDefault();
    
    // Validate required fields
    if (!formData.name || !formData.name.trim()) {
      setMessage("Student name is required");
      return;
    }
    
    if (!formData.class || !formData.division) {
      setMessage("Class and Division are required");
      return;
    }
    
    if (!formData.subjects || formData.subjects.length === 0) {
      setMessage("Please select at least one subject");
      return;
    }

    // Validate academic year format
    const yearRegex = /^\d{4}-\d{2}$/;
    if (!yearRegex.test(formData.academic_year)) {
      setMessage("Academic Year must be in format YYYY-YY (e.g., 2024-25)");
      return;
    }
    
    setLoading(true);
    setMessage("");

    try {
      // Call the API directly
      const response = await API.post("/api/users/create", {
        name: formData.name.trim(),
        email: formData.email?.trim() || null,
        password: formData.password || null, // Let backend generate if empty
        gender: formData.gender,
        class: formData.class,
        division: formData.division,
        academic_year: formData.academic_year,
        subjects: formData.subjects,
        parent_name: formData.parent_name?.trim() || null,
        parent_email: formData.parent_email?.trim() || null
      });

      if (response.data.success) {
        setMessage(`✅ Student created successfully! 
          User Code: ${response.data.student?.usercode || 'Generated by system'}
          Admission No: ${response.data.student?.admission_no || 'Generated by system'}`);
        
        // If parent component provided onSubmit callback, call it
        if (onSubmit) {
          onSubmit(formData);
        }
        
        // Reset form after successful submission
        setTimeout(() => {
          setFormData({
            user_code: "",
            admission_no: "",
            name: "",
            email: "",
            password: "",
            class: "",
            division: "",
            gender: "M",
            parent_name: "",
            parent_email: "",
            subjects: [],
            academic_year: "2024-25"
          });
          setMessage("");
          if (onClose) onClose();
        }, 3000);
      } else {
        setMessage(response.data.error || "Failed to create student");
      }
    } catch (err) {
      console.error("Error creating student:", err);
      setMessage(err.response?.data?.error || "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSubjectChange = (subject) => {
    const updatedSubjects = formData.subjects.includes(subject)
      ? formData.subjects.filter(s => s !== subject)
      : [...formData.subjects, subject];
    
    setFormData({
      ...formData,
      subjects: updatedSubjects
    });
  };

  const handleInputChange = (field, value) => {
    setFormData({
      ...formData,
      [field]: value
    });
    // Clear message when user starts typing
    if (message) setMessage("");
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Message Display */}
      {message && (
        <div className={`p-4 rounded-xl ${message.includes("✅") ? 'bg-green-50 text-green-800 border border-green-200' : 'bg-red-50 text-red-800 border border-red-200'}`}>
          {message.split('\n').map((line, i) => (
            <span key={i}>
              {line}
              <br />
            </span>
          ))}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* User Code - Show placeholder since backend generates it */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            User Code
          </label>
          <div className="flex items-center">
            <input
              type="text"
              value="Auto-generated by system"
              readOnly
              className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-gray-500 cursor-not-allowed"
            />
            <span className="ml-2 px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-lg">
              Auto
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Will be assigned as STU-0001, STU-0002, etc.
          </p>
        </div>

        {/* Admission No - Show placeholder since backend generates it */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Admission No
          </label>
          <div className="flex items-center">
            <input
              type="text"
              value="Auto-generated by system"
              readOnly
              className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-gray-500 cursor-not-allowed"
            />
            <span className="ml-2 px-2 py-1 text-xs bg-green-100 text-green-800 rounded-lg">
              Auto
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Will be assigned as ADM0001, ADM0002, etc.
          </p>
        </div>

        {/* Full Name - Required */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Full Name *
          </label>
          <input
            type="text"
            required
            value={formData.name}
            onChange={(e) => handleInputChange("name", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Enter student name"
          />
        </div>

        {/* Gender - Required */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Gender *
          </label>
          <select
            value={formData.gender}
            onChange={(e) => handleInputChange("gender", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
          >
            <option value="M">Male</option>
            <option value="F">Female</option>
            <option value="O">Other</option>
          </select>
        </div>

        {/* Email */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Email
          </label>
          <input
            type="email"
            value={formData.email}
            onChange={(e) => handleInputChange("email", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="student@example.com"
          />
        </div>

        {/* Password */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Password
          </label>
          <input
            type="password"
            value={formData.password}
            onChange={(e) => handleInputChange("password", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Leave blank for auto-generation"
          />
          <p className="text-xs text-gray-500 mt-1">
            Leave blank to generate random password
          </p>
        </div>

        {/* Class - Required */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Class *
          </label>
          <select
            value={formData.class}
            onChange={(e) => handleInputChange("class", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            required
          >
            <option value="">Select Class</option>
            {CLASSES.map((cls) => (
              <option key={cls} value={cls}>{cls}</option>
            ))}
          </select>
        </div>

        {/* Division - Required */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Division *
          </label>
          <select
            value={formData.division}
            onChange={(e) => handleInputChange("division", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            required
          >
            <option value="">Select Division</option>
            {DIVISIONS.map((div) => (
              <option key={div} value={div}>{div}</option>
            ))}
          </select>
        </div>

        {/* Parent Name */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Parent Name
          </label>
          <input
            type="text"
            value={formData.parent_name}
            onChange={(e) => handleInputChange("parent_name", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="Parent/Guardian name"
          />
        </div>

        {/* Parent Email */}
        <div className="input-group">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Parent Email
          </label>
          <input
            type="email"
            value={formData.parent_email}
            onChange={(e) => handleInputChange("parent_email", e.target.value)}
            className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
            placeholder="parent@example.com"
          />
        </div>
      </div>

      {/* Subjects Selection - Multiple */}
      <div className="input-group pt-2">
        <label className="block text-sm font-medium text-gray-700 mb-3">
          Select Subjects * (Choose at least one)
        </label>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 p-4 bg-gray-50 rounded-xl">
          {SUBJECTS.map((subject) => (
            <div key={subject} className="flex items-center">
              <input
                type="checkbox"
                id={`subject-${subject}`}
                checked={formData.subjects.includes(subject)}
                onChange={() => handleSubjectChange(subject)}
                className="h-5 w-5 text-purple-600 rounded focus:ring-purple-500"
              />
              <label
                htmlFor={`subject-${subject}`}
                className="ml-3 text-sm font-medium text-gray-700 cursor-pointer"
              >
                {subject}
              </label>
            </div>
          ))}
        </div>
        {formData.subjects.length > 0 && (
          <div className="mt-3">
            <p className="text-sm text-gray-600">
              Selected: <span className="font-semibold text-purple-600">
                {formData.subjects.join(", ")}
              </span>
            </p>
          </div>
        )}
      </div>

      {/* Academic Year */}
      <div className="input-group">
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Academic Year *
        </label>
        <input
          type="text"
          value={formData.academic_year}
          onChange={(e) => handleInputChange("academic_year", e.target.value)}
          className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition"
          placeholder="2024-25"
          required
        />
        <p className="text-xs text-gray-500 mt-1">
          Format: YYYY-YY (e.g., 2024-25)
        </p>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 pt-6 border-t">
        <button
          type="button"
          onClick={onClose}
          className="flex-1 px-6 py-3.5 border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-all duration-200 font-medium"
          disabled={loading}
        >
          Cancel
        </button>
        <button
          type="submit"
          className="flex-1 px-6 py-3.5 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-xl hover:shadow-lg hover:scale-[1.02] transition-all duration-200 font-semibold disabled:opacity-70 disabled:cursor-not-allowed"
          disabled={loading}
        >
          {loading ? "Creating..." : (initialData.admission_no ? "Update Student" : "Create Student")}
        </button>
      </div>
    </form>
  );
}