// import React, { useState } from "react";
// import API from "../../api";

// function StudentRegister() {
//   const [formData, setFormData] = useState({
//     name: "",
//     email: "",
//     password: "",
//     gender: "M",
//     class: "",
//     division: "",
//     academic_year: "2024-25",
//     subjects: [],
//     parent_name: "",
//     parent_email: ""
//   });
  
//   const [message, setMessage] = useState("");
//   const [showPassword, setShowPassword] = useState(false);

//   const CLASSES = ["Class 1", "Class 2", "Class 3", ];
//   const DIVISIONS = ["A", "B", "C"];
//   const SUBJECTS = ["English", "Maths", "Science", ];

//   const styles = {
//     container: {
//       maxWidth: "600px",
//       margin: "30px auto",
//       padding: "30px",
//       background: "#f5f5f5",
//       borderRadius: "8px",
//       boxShadow: "0 8px 15px rgba(0, 0, 0, 0.1)",
//       fontFamily: "Arial, sans-serif",
//     },
//     heading: {
//       textAlign: "center",
//       marginBottom: "25px",
//       color: "#333",
//     },
//     form: {
//       display: "flex",
//       flexDirection: "column",
//     },
//     input: {
//       padding: "12px 15px",
//       marginBottom: "15px",
//       border: "1.5px solid #ddd",
//       borderRadius: "5px",
//       fontSize: "16px",
//       outline: "none",
//       width: "100%",
//       boxSizing: "border-box"
//     },
//     select: {
//       padding: "12px 15px",
//       marginBottom: "15px",
//       border: "1.5px solid #ddd",
//       borderRadius: "5px",
//       fontSize: "16px",
//       outline: "none",
//       width: "100%",
//       boxSizing: "border-box",
//       backgroundColor: "white"
//     },
//     button: {
//       padding: "12px 20px",
//       backgroundColor: "#3fe774ff",
//       color: "white",
//       border: "none",
//       fontSize: "18px",
//       borderRadius: "5px",
//       cursor: "pointer",
//       marginTop: "10px"
//     },
//     message: {
//       marginTop: "20px",
//       textAlign: "center",
//       fontWeight: "600",
//       color: "green",
//     },
//     error: {
//       marginTop: "20px",
//       textAlign: "center",
//       fontWeight: "600",
//       color: "red",
//     },
//     grid: {
//       display: "grid",
//       gridTemplateColumns: "1fr 1fr",
//       gap: "15px",
//       marginBottom: "15px"
//     },
//     checkboxGroup: {
//       marginBottom: "15px",
//       padding: "15px",
//       backgroundColor: "white",
//       borderRadius: "5px",
//       border: "1.5px solid #ddd"
//     },
//     checkbox: {
//       marginRight: "8px",
//       marginBottom: "8px"
//     },
//     label: {
//       display: "block",
//       marginBottom: "5px",
//       fontWeight: "600",
//       color: "#555"
//     },
//     passwordToggle: {
//       backgroundColor: "#f0f0f0",
//       border: "1px solid #ddd",
//       padding: "8px 12px",
//       borderRadius: "4px",
//       cursor: "pointer",
//       fontSize: "14px",
//       marginLeft: "10px"
//     }
//   };

//   const handleInputChange = (e) => {
//     const { name, value } = e.target;
//     setFormData({
//       ...formData,
//       [name]: value
//     });
//   };

//   const handleSubjectChange = (subject) => {
//     setFormData(prev => ({
//       ...prev,
//       subjects: prev.subjects.includes(subject)
//         ? prev.subjects.filter(s => s !== subject)
//         : [...prev.subjects, subject]
//     }));
//   };

//   async function handleRegister(e) {
//     e.preventDefault();

//     // Validation
//     if (!formData.name || !formData.email || !formData.class || !formData.division) {
//       setMessage("Please fill all required fields!");
//       return;
//     }

//     if (formData.subjects.length === 0) {
//       setMessage("Please select at least one subject!");
//       return;
//     }

//     try {
//       // Send all student data to backend
//       const response = await API.post("/users/create", {
//         name: formData.name,
//         email: formData.email,
//         password: formData.password || "student@123", // Default password if not provided
//         gender: formData.gender,
//         class: formData.class,
//         division: formData.division,
//         academic_year: formData.academic_year,
//         subjects: formData.subjects,
//         parent_name: formData.parent_name,
//         parent_email: formData.parent_email
//       });

//       if (response.data.success) {
//         setMessage(`✅ Student registered successfully! 
//           User Code: ${response.data.student?.usercode || 'Generated by system'}
//           Admission No: ${response.data.student?.admission_no || 'Generated by system'}`);
        
//         // Reset form
//         setFormData({
//           name: "",
//           email: "",
//           password: "",
//           gender: "M",
//           class: "",
//           division: "",
//           academic_year: "2024-25",
//           subjects: [],
//           parent_name: "",
//           parent_email: ""
//         });
//       } else {
//         setMessage(response.data.error || "Registration failed!");
//       }

//     } catch (error) {
//       console.error("Registration error:", error);
//       setMessage(error.response?.data?.error || "Something went wrong!");
//     }
//   }

//   return (
//     <div style={styles.container}>
//       <h2 style={styles.heading}>Register New Student</h2>
//       <p style={{ textAlign: "center", marginBottom: "20px", color: "#666" }}>
//         Fill in student details below
//       </p>

//       <form style={styles.form} onSubmit={handleRegister}>
//         {/* Basic Information */}
//         <div style={styles.grid}>
//           <div>
//             <label style={styles.label}>Full Name *</label>
//             <input
//               type="text"
//               name="name"
//               placeholder="Enter student name"
//               value={formData.name}
//               onChange={handleInputChange}
//               style={styles.input}
//               required
//             />
//           </div>
          
//           <div>
//             <label style={styles.label}>Email *</label>
//             <input
//               type="email"
//               name="email"
//               placeholder="student@example.com"
//               value={formData.email}
//               onChange={handleInputChange}
//               style={styles.input}
//               required
//             />
//           </div>
//         </div>

//         <div style={styles.grid}>
//           <div>
//             <label style={styles.label}>Gender *</label>
//             <select
//               name="gender"
//               value={formData.gender}
//               onChange={handleInputChange}
//               style={styles.select}
//             >
//               <option value="M">Male</option>
//               <option value="F">Female</option>
//               <option value="O">Other</option>
//             </select>
//           </div>
          
//           <div>
//             <label style={styles.label}>Password</label>
//             <div style={{ display: "flex", alignItems: "center" }}>
//               <input
//                 type={showPassword ? "text" : "password"}
//                 name="password"
//                 placeholder="Leave blank for auto-generation"
//                 value={formData.password}
//                 onChange={handleInputChange}
//                 style={{...styles.input, marginBottom: "0", flex: "1"}}
//               />
//               <button
//                 type="button"
//                 onClick={() => setShowPassword(!showPassword)}
//                 style={styles.passwordToggle}
//               >
//                 {showPassword ? "Hide" : "Show"}
//               </button>
//             </div>
//             <small style={{ color: "#666", fontSize: "12px" }}>
//               Leave blank for auto-generated password
//             </small>
//           </div>
//         </div>

//         {/* Class Information */}
//         <div style={styles.grid}>
//           <div>
//             <label style={styles.label}>Class *</label>
//             <select
//               name="class"
//               value={formData.class}
//               onChange={handleInputChange}
//               style={styles.select}
//               required
//             >
//               <option value="">Select Class</option>
//               {CLASSES.map(cls => (
//                 <option key={cls} value={cls}>{cls}</option>
//               ))}
//             </select>
//           </div>
          
//           <div>
//             <label style={styles.label}>Division *</label>
//             <select
//               name="division"
//               value={formData.division}
//               onChange={handleInputChange}
//               style={styles.select}
//               required
//             >
//               <option value="">Select Division</option>
//               {DIVISIONS.map(div => (
//                 <option key={div} value={div}>{div}</option>
//               ))}
//             </select>
//           </div>
//         </div>

//         <div style={styles.grid}>
//           <div>
//             <label style={styles.label}>Academic Year *</label>
//             <input
//               type="text"
//               name="academic_year"
//               placeholder="2024-25"
//               value={formData.academic_year}
//               onChange={handleInputChange}
//               style={styles.input}
//               required
//             />
//           </div>
          
//           <div>
//             <label style={styles.label}>Parent Name</label>
//             <input
//               type="text"
//               name="parent_name"
//               placeholder="Parent/Guardian name"
//               value={formData.parent_name}
//               onChange={handleInputChange}
//               style={styles.input}
//             />
//           </div>
//         </div>

//         <div>
//           <label style={styles.label}>Parent Email</label>
//           <input
//             type="email"
//             name="parent_email"
//             placeholder="parent@example.com"
//             value={formData.parent_email}
//             onChange={handleInputChange}
//             style={styles.input}
//           />
//         </div>

//         {/* Subjects Selection */}
//         <div style={styles.checkboxGroup}>
//           <label style={{...styles.label, marginBottom: "10px"}}>Subjects * (Select at least one)</label>
//           <div>
//             {SUBJECTS.map(subject => (
//               <div key={subject} style={{ display: "inline-block", marginRight: "20px", marginBottom: "10px" }}>
//                 <input
//                   type="checkbox"
//                   id={`subject-${subject}`}
//                   checked={formData.subjects.includes(subject)}
//                   onChange={() => handleSubjectChange(subject)}
//                   style={styles.checkbox}
//                 />
//                 <label htmlFor={`subject-${subject}`} style={{ cursor: "pointer" }}>
//                   {subject}
//                 </label>
//               </div>
//             ))}
//           </div>
//           {formData.subjects.length > 0 && (
//             <div style={{ marginTop: "10px", padding: "8px", backgroundColor: "#e8f4fc", borderRadius: "4px" }}>
//               <strong>Selected:</strong> {formData.subjects.join(", ")}
//             </div>
//           )}
//         </div>

//         <button type="submit" style={styles.button}>
//           Register Student
//         </button>
//       </form>

//       {message && (
//         <p style={message.includes("✅") ? styles.message : styles.error}>
//           {message.split('\n').map((line, i) => (
//             <span key={i}>
//               {line}
//               <br />
//             </span>
//           ))}
//         </p>
//       )}

//       <div style={{ marginTop: "20px", padding: "15px", backgroundColor: "#fff3cd", borderRadius: "5px", border: "1px solid #ffeaa7" }}>
//         <strong>Note:</strong>
//         <ul style={{ margin: "10px 0 0 20px", padding: "0" }}>
//           <li>User Code and Admission Number will be auto-generated</li>
//           <li>If password is not provided, system will generate one</li>
//           <li>All fields marked with * are required</li>
//         </ul>
//       </div>
//     </div>
//   );
// }

// export default StudentRegister;